# Generated by Django 5.1.6 on 2025-02-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_program', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_score', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.course')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_grading.gradesystem')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOverallGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=200, null=True)),
                ('csa', models.FloatField(blank=True, null=True)),
                ('overall_performance', models.CharField(blank=True, max_length=100, null=True)),
                ('year_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.program')),
            ],
        ),
    ]
