# Generated by Django 5.1.6 on 2025-02-24 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('number_of_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=250, null=True)),
                ('presence', models.CharField(blank=True, choices=[('Virtual', 'Virtual'), ('In-person', 'In-person')], max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('event_contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('event_contact_email', models.CharField(blank=True, max_length=250, null=True)),
                ('event_contact_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='event_documents/')),
                ('document_name', models.CharField(blank=True, max_length=250, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('other_names', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_contact', models.CharField(max_length=250)),
                ('email_address', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
        ),
    ]
