# Generated by Django 5.1.6 on 2025-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
