# Generated by Django 5.1.6 on 2025-03-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('In House', 'In House'), ('External', 'External')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
