# Generated by Django 5.1.6 on 2025-03-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_department_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
