# Generated by Django 5.1.6 on 2025-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='phone_contact',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
