# Generated by Django 5.1.6 on 2025-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
