# Generated by Django 5.1.6 on 2025-02-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_program', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.program')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_options', models.CharField(blank=True, max_length=250, null=True)),
                ('program_fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.programfees')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('percentage_cleared', models.FloatField(blank=True, default=0.0, null=True)),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financestatement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail')),
            ],
        ),
    ]
