# Generated by Django 5.1.6 on 2025-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymenttrail_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttrail',
            name='new_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
