# Generated by Django 5.1.6 on 2025-03-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_paymenttrail_new_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinance',
            name='student_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
