# Generated by Django 5.1.6 on 2025-03-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_studentfinance_student_balance'),
        ('marketing', '0010_admission_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('percentage_cleared', models.FloatField(blank=True, default=0.0, null=True)),
                ('student_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financestatement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.admission')),
            ],
        ),
    ]
