# Generated by Django 5.1.6 on 2025-03-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_program', '0008_alter_program_assistant_program_officer_and_more'),
        ('finance', '0006_admissionfinance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPaymentTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('new_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('admission_finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_trails', to='finance.admissionfinance')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_program.program')),
            ],
        ),
    ]
