# Generated by Django 5.1.6 on 2025-03-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_admissionpaymenttrail'),
        ('marketing', '0011_admission_gender_admission_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionfinance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_finance', to='marketing.admission'),
        ),
    ]
