# Generated by Django 5.1.6 on 2025-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_admissionfinance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionfinance',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
