# Generated by Django 5.1.6 on 2025-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_admissionfinance_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionfinance',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Direct Payment', 'Direct Payment'), ('Bank', 'Bank'), ('Other', 'Other')], max_length=250, null=True),
        ),
    ]
