# Generated by Django 5.1.6 on 2025-03-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_admission_admissiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
