# Generated by Django 5.1.6 on 2025-03-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_program', '0008_alter_program_assistant_program_officer_and_more'),
        ('marketing', '0004_admission_cv_admission_passport_front_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='program_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_program.programcover'),
        ),
    ]
