# Generated by Django 5.1.6 on 2025-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_admission_program_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('documents_under_review', 'Documents Under Review'), ('documents_review_cleared', 'Documents Review Cleared'), ('cleared_by_admissions', 'Cleared By Admissions'), ('awaiting_financial_clearance', 'Awaiting Financial Clearance'), ('student_cleared_financially', 'Student Cleared Financially'), ('admission_completed', 'Admission Completed'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
