# Generated by Django 5.1.6 on 2025-03-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_admission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissiontranscript',
            name='admission',
        ),
        migrations.AddField(
            model_name='admission',
            name='certificate_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='admission',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='admission',
            name='transcript_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='AdmissionCertificate',
        ),
        migrations.DeleteModel(
            name='AdmissionTranscript',
        ),
    ]
