# Generated by Django 5.1.6 on 2025-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_admission_certificate_files_alter_admission_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
