# Generated by Django 5.1.6 on 2025-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_admission_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
