# Generated by Django 5.1.6 on 2025-03-25 12:05

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_admission_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
