# Generated by Django 5.1.6 on 2025-02-24 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_program', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.course'),
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='academic_program.course'),
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic_program.lecturer'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_program.lecturertype'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_program.programcover'),
        ),
        migrations.AddField(
            model_name='programparticipant',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.program'),
        ),
        migrations.AddField(
            model_name='programparticipant',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail'),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.course'),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_program.programtype'),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.program'),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail'),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedtranscriptrequest',
            name='transcript_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_program.transcriptrequest'),
        ),
    ]
