# Generated by Django 5.1.6 on 2025-03-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_program', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='assistant_program_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_program_officer', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_officer', to='students.studentenrollment'),
        ),
    ]
