# Generated by Django 5.1.6 on 2025-03-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_program', '0003_program_assistant_program_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='year',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
