# Generated by Django 5.1.6 on 2025-03-14 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_program', '0004_program_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramScheduleDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('program_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_dates', to='academic_program.programschedule')),
            ],
        ),
    ]
