# Generated by Django 5.1.6 on 2025-03-15 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_program', '0005_programscheduledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='year',
        ),
        migrations.CreateModel(
            name='CourseCovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_cover', models.CharField(blank=True, max_length=250, null=True)),
                ('course_name', models.CharField(max_length=250)),
                ('course_description', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('flag', models.BooleanField(default=True)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_covers', to='academic_program.lecturer')),
            ],
        ),
    ]
