# Generated by Django 5.1.6 on 2025-03-15 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_program', '0006_remove_program_year_coursecovers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecovers',
            name='program_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_program.programcover'),
        ),
    ]
